Fixes #30661 - fix seed order of templates
theforeman/foreman_salt pull request #138
Opened 2021-01-18 12:33 UTC by m-bucher

Looks like the `salt_run_function_-_ssh_default.erb` has to be seeded first.

2021-06-17 07:25 UTC, sbernhard requested changes

2021-06-17 07:25 UTC, sbernhard commented on db/seeds.d/76-job_templates.rb
> +        dirs = Dir[File.join("#{ForemanSalt::Engine.root}/app/views/foreman_salt/"\
Wouldn't it be better to name the var "templates" or "jobs" instead of "dirs"?

2021-06-17 07:25 UTC, sbernhard commented on db/seeds.d/76-job_templates.rb
> +        first = dirs.select { |d| d =~ /function/ }
I would prefer to check for "salt_run_function" instead of regex function. Like
d.start_with('salt_run_function')

2022-01-26 16:40 UTC, danny-smit commented
I'm running into this issue as well. Since this pull request became stale, I'm willing to create a new one if to get it done if desired.

2022-01-26 22:53 UTC, merged